### ISSUE TITLE
Body text is not showing completely it's cutting out.

### ISSUE THREAD

**Issue by uasghar-smile** [tschoffelen/react-native-email-link#103]
Hi I am having an issue while trying to send an email body text is not showing completely

**Comment by uasghar-smile** [comment]
Hi @tschoffelen can you please assist me on this why my body text is not being shown completely.
Platform: "IOS"

**Comment by jahirfiquitiva** [comment]
@tschoffelen @danielmark0116 

We are facing this very same issue.

This is a text we are using to test:
```
! " # $ % & ' ( ) * + , - . / 0 1 2 3 4 5 6 7 8 9 : ; < = > ? @ A B C D E F G H I J K L M N O P Q R S T U V W X Y Z [ \ ] ^ _ ` a b c d e f g h i j k l m n o p q r s t u v w x y z { | } ~
```


These are the results of our tests:

**Without `encodeBody`, or `encodeBody: false`**

| Apple Email | Gmail | Outlook |
| ------- | ------- | ------- |
| ![IMG_2504](https://github.com/includable/react-native-email-link/assets/10360816/aef4416f-0ad6-4f45-bf60-25b00bca22ee) | ![IMG_2505](https://github.com/includable/react-native-email-link/assets/10360816/df50f965-20de-4797-835d-de2a88433d68) | ![IMG_2506](https://github.com/includable/react-native-email-link/assets/10360816/33a806fd-36e5-4fe4-8a4f-2284771e762e) |
  


**With `encodeBody: true`**

| Apple Email | Gmail | Outlook |
| ------- | ------- | ------- |
| ![IMG_2507](https://github.com/includable/react-native-email-link/assets/10360816/d56104fd-46ed-439a-a6d0-f8ac14bd9872) | ![IMG_2508](https://github.com/includable/react-native-email-link/assets/10360816/cd321906-d845-49b9-8990-774d3ad570bc) | ![IMG_2509](https://github.com/includable/react-native-email-link/assets/10360816/408f27cd-0dbf-4fbe-909e-9ae1a26c84a5) |

In this one, I think spaces (` `) should not be encoded.

**Comment by tschoffelen** [comment]
Thanks for testing that @jahirfiquitiva!

Ideally, I think we should customise if/how we encode the body based on the email client chosen, and deprecate the `encodeBody` parameter. I don't have time in the foreseeable future to work on this myself, but would be more than happy to accept a PR of course!

**Comment by jahirfiquitiva** [comment]
This should not be marked as stale, the issue is still present

**Comment by tschoffelen** [comment]
Heya @jahirfiquitiva! Happy to accept a PR to fix this, I am not currently using the email composer option of the lib myself, and don't have time to look into it at the moment

**Comment by jahirfiquitiva** [comment]
@tschoffelen  I don't feel confident in my `react-native` knowledge as to be able to provide a PR to fix this. But hopefully in the near future.

**Comment by pke** [comment]
Spaces could be encoded as "+", I'll check if the clients support that.

**Comment by tschoffelen** [comment]
Yeah it seems to differ between clients - appreciate it!
