### ISSUE TITLE
when email client is opened - remains opened after sending mail

### ISSUE THREAD

**Issue by surapanenirajesh** [tschoffelen/react-native-email-link#137]
Hi can we have some trigger to close the email client app that is opened from React Native using this library which opens a mail client app, However after opening the client and sending mail the email client application still remains open 

Can we have some way to close the opened app

**Comment by tschoffelen** [comment]
I don't think there is a way to do this - or at least not one I'm aware of. Happy to accept PRs to add this functionality though!

**Comment by surapanenirajesh** [comment]
@tschoffelen  thanks for the reply, I will look around if i get a solution i am happy to raise a PR. Please hold on to this thread for some time
