### ISSUE TITLE
OpenInbox() of react-native-email-link is not working

### ISSUE THREAD

**Issue by assylhan-dev** [tschoffelen/react-native-email-link#140]
I was going to open the email inbox in react native using react-native-email-link.
But the app can't launch the email app and there are no anything warning or error.
What should I do to resolve this?
![image](https://github.com/user-attachments/assets/fd9a73b9-e12e-4844-9679-b82a1c30d024)
I have used "react-native": "0.73.6" for this app.

**Comment by tschoffelen** [comment]
Hi there!

Not sure if I can help, but maybe the following will shine a light on it:
- Are you using Expo or just plain react native?
- Are you running in the simulator or on device?
- Is this on iOS or android?

**Comment by tiger01815** [comment]
Thank you for your reply.

- I used react-native-cli for my project.
- I am developing on Android emulator now.
- The current screenshot is showing code of android side.

**Comment by tschoffelen** [comment]
In that case I don't know why that would be. Only things I can think of:

- Did you re-build the app after installing the lib?
- Did you enable the new RN architecture? I think this library might not yet work with that
