### ISSUE TITLE
The title, message, cancelLabel, removeText, and defaultEmailLabel attributes of the InboxOptions object do not take effect.

### ISSUE THREAD

**Issue by kunfanc** [tschoffelen/react-native-email-link#141]
Q1. In Android, the settings of the title, message, cancelLabel, removeText, and defaultEmailLabel attributes do not take effect.
Q2. The app attribute is not set for iOS. Even if the attribute of title, message, cancelLabel, removeText, and defaultEmailLabel is set, they are not used.
Q3. After the app attribute in iOS is set to gmail or outlook, the title, message, cancelLabel, removeText, and defaultEmailLabel are not used even if the attributes are set.
Q4. How can I check whether attributes such as title, message, cancelLabel, removeText, and defaultEmailLabel take effect in iOS or Android?

**Comment by tschoffelen** [comment]
I'm not sure if I fully understand. 

These attributes for the text of the dialog should have effect, but only if there's more than one app available, otherwise the first app will be opened immediately.
