### ISSUE TITLE
Android: allow for starting the email app in the same task

### ISSUE THREAD

**Issue by udeyrishi** [tschoffelen/react-native-email-link#29]
The Android [code](https://github.com/leanmotherfuckers/react-native-email-link/blob/master/android/src/main/java/com/facebook/react/modules/email/EmailModule.java#L62) currently forces that the email app will be started in a new task. Some use cases might require that to not be the case. It'd be nice if there were an optional param that allowed users to stay in the current task.

**Comment by tschoffelen** [comment]
Feel free to submit a PR for that. My understanding of how Android's system of tasks and intents works is too limited I'm afraid.

**Comment by udeyrishi** [comment]
Opened up the PR here: https://github.com/leanmotherfuckers/react-native-email-link/pull/30. Would love to get a release out with this change 🙏

**Comment by tschoffelen** [comment]
I saw you closed the PR. Did the approach end up not working?

**Comment by udeyrishi** [comment]
It needs a little more love. I had to dig into the `getLaunchIntentForPackage` source, and I noticed that that function is also adding the new task flag. So we need to explicitly remove that flag as well. Sorry I didn't get a chance to open a PR with that fix; I'll put it out soon.

**Comment by tschoffelen** [comment]
Ah, great, thanks for the update!

**Comment by udeyrishi** [comment]
I'm actually struggling to get the project to compile in a fairly recent setup of android studio 😅 Looks like the build.gradle files haven't been updated in a while. I might open up a PR to bump that first.
