### ISSUE TITLE
`openInbox()` fails when called without an object

### ISSUE THREAD

**Issue by fnando** [tschoffelen/react-native-email-link#40]
The README instruction is misleading; if you call `openInbox()`, you'll see an error like `TypeError: Cannot use 'in' operator to search for 'app' in undefined`. The fix is either requiring the options object to always be provided (e.g. `openInbox({})`), or changing `getApp` to default to an empty object.

I'd like to know what would be the proper fix to come up with a pull request.

Thanks!

**Comment by tschoffelen** [comment]
Oh! That is obviously not the intended behaviour.

I think we just need to add a default value for the `options` param in `openInbox`: https://github.com/tschoffelen/react-native-email-link/blob/master/index.ios.js#L237

**Comment by fnando** [comment]
There you go: https://github.com/tschoffelen/react-native-email-link/pull/41
