### ISSUE TITLE
How do I add to and subject for android?

### ISSUE THREAD

**Issue by jazzymb7** [tschoffelen/react-native-email-link#43]

**Comment by tschoffelen** [comment]
Currently, as the README states, only the `openInbox` function is available on Android. There's no `openComposer` implementation for Android yet, but I welcome a PR of course!

**Comment by gekitz** [comment]
This is how it could work. 
https://github.com/gekitz/react-native-email-link/pull/1

**Comment by tschoffelen** [comment]
Awesome @gekitz! Mind opening a PR with that change in this repo? I'd gladly merge it!

**Comment by gekitz** [comment]
sure, here you go. https://github.com/tschoffelen/react-native-email-link/pull/54 I hope you don't mind the automatic code reformatting.
