### ISSUE TITLE
[Android] openInbox() not working 

### ISSUE THREAD

**Issue by yelkamel** [tschoffelen/react-native-email-link#44]
When I use the function openInBox() in iOS everything seem ok but in Android it's not working.

My environment:

  npmPackages:
    react: 16.9.0
    react-native:  0.61.4
    react-native-email-link:  ^1.6.4

**Comment by tschoffelen** [comment]
Hi! Do you get any error? Also, do you have a supported email app installed on the device you're using to test this?

**Comment by yelkamel** [comment]
I don't get any error and everything work with react-native-mail-launcher ...
