### ISSUE TITLE
How to get working with react-native-web?

### ISSUE THREAD

**Issue by fractalmarc** [tschoffelen/react-native-email-link#45]
Hi there, how might one get this working with react-native-web?

When I run `expo start --web`, I get the error 
`Module not found: Can't resolve 'react-native-email-link' in '/Users/mgelfo/projects/fun/GMI_Mobile/src/screens'`

Otherwise it's working great on mobile!

**Comment by tschoffelen** [comment]
I personally don't really have any experience with react-native-web, so I'm not sure what needs to change in this library to make it work. I'd have assumed it would work out of the box, since it only depends on `Linking` from `react-native`.

**Comment by tschoffelen** [comment]
Hi @fractalmarc, any luck getting this to work eventually?

**Comment by tschoffelen** [comment]
Closing this one for now, since there doesn't seem to be too much demand for RN web support at the moment. Still welcome a PR though!

**Comment by HannahCarney** [comment]
I want it

**Comment by tschoffelen** [comment]
I don't have any experience with react-native-web, so not sure what we would need to do for this, but of course very happy to accept a PR to implement this functionality!
