### ISSUE TITLE
Add arguments to the usage example

### ISSUE THREAD

**Issue by switch13** [tschoffelen/react-native-email-link#49]
Sorry, I'm new at this. Is there a way you can show some example usage for implementing some of the arguments in the openInBox() in the Readme? Or point me somewhere with already implemented examples? I struggle with getting started with these. Thanks in advance!

**Comment by tschoffelen** [comment]
Hi! I can see where the confusion comes from. The arguments should be passed in as an object:

```
import { openInbox } from 'react-native-email-link'

openInbox({
	message: 'Whatcha wanna do?',
	cancelLabel: 'Go back!'
})
```

**Comment by switch13** [comment]
Thank so much!!! that was quick! Are you ok if a do a pull request for the readme file?

**Comment by tschoffelen** [comment]
@switch13 Sure, feel free to do a PR to clarify the README.
