### ISSUE TITLE
This package is not working for me

### ISSUE THREAD

**Issue by bilalyaqoob** [tschoffelen/react-native-email-link#51]
"react-native-email-link": "^1.4.0",

react-native-cli: 2.0.1
react-native: 0.59.9

it is showing no change in my app

**Comment by tschoffelen** [comment]
Can you give some more details about how you're using the library (i.e. a snippet of your code)?

**Comment by bilalyaqoob** [comment]
import { openInbox, openComposer } from 'react-native-email-link'

onSend = () => {
openInbox({
    title:"abcd",
    message: 'Whatcha wanna do?',
    cancelLabel: 'Go back!'
})
}


<RaisedTextButton
                onPress={() => this.onSend()}  
                title='Send Email'
                titleColor='#FFF'
                style={ThemeStyle.buttonColor}
            />

**Comment by tschoffelen** [comment]
Sorry for the slow response.

That seems completely fine. Is it possible your testing the app on a device or simulator that doesn't have any of the supported email apps installed?

Alternatively, if you're using a version of React Native under 0.60.0, you might need to manually link the library for use on Android, as mentioned in the [installation section of the README](https://github.com/tschoffelen/react-native-email-link#installation).

In almost all cases a warning about this would show up in your console, though.

**Comment by bilalyaqoob** [comment]
I also did that 
<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>message</string>
		<string>readdle-spark</string>
		<string>airmail</string>
		<string>ms-outlook</string>
		<string>gmail</string>
		<string>googlegmail</string>
		<string>inbox-gmail</string>
		<string>ymail</string>
		<string>superhuman</string>
	</array>

and i have gmail installed and yahoo mail installed

**Comment by bilalyaqoob** [comment]
when i use this 
 openComposer({
          title: "abcd",
          to: 'yourEmail@address.com',
          subject: 'Wanna change the world?',
          body: 'This is our year!',
          message: 'Whatcha wanna do?',
          cancelLabel: 'Go back!'
        })
      } catch (error) {
        console.log(error);
      }

i got this error:
Possible Unhandled Promise Rejection (id: 0):
W/ReactNativeJS(16759): EmailException {
W/ReactNativeJS(16759):   "message": "openComposer not available on Anroid",
W/ReactNativeJS(16759):   "name": "EmailException",
W/ReactNativeJS(16759): }

**Comment by bilalyaqoob** [comment]
when i use   
openInbox({
          title: "abcd",
          to: 'bilalyaqoob111996@gmail.com',
          subject: 'Wanna change the world?',
          body: 'This is our year!',
          message: 'Whatcha wanna do?',
          cancelLabel: 'Go back!'
        })
      } catch (error) {
        console.log(error);
      }

i got this error
Possible Unhandled Promise Rejection (id: 4):
W/ReactNativeJS(16759): TypeError: null is not an object (evaluating '_reactNative.NativeModules.Email.open')

**Comment by tschoffelen** [comment]
That sounds like the native Android module is not installed correctly - did you make sure to rebuild the native part of your app after adding this library?
