### ISSUE TITLE
Clicking Cancel in the ActionSheet throws unhandled promise exception

### ISSUE THREAD

**Issue by ShaharyarMaroof** [tschoffelen/react-native-email-link#52]
I am calling the openInbox function on a button click from my app. The ActionSheet for the Email App Selection opens up showing Gmail , Mail and the Cancel option.

If I click on the cancel option the following exception occurs:
![IMG_0528](https://user-images.githubusercontent.com/10959027/75357354-11e84580-58d3-11ea-899b-17902b39d749.PNG)

**Comment by tschoffelen** [comment]
Oh, that's obviously not the intended behaviour. Feel free to submit a PR if you have the time. 

Otherwise a quick fix is put a try-catch statement around the call, although that's obviously not the cleanest solution...
