### ISSUE TITLE
Does this package work with an Expo app ? 

### ISSUE THREAD

**Issue by bedoxonline** [tschoffelen/react-native-email-link#55]
Hi, 

firstly thank you for letting this package be open source ! 

So, I have a React Native app that runs with Expo 3.11.7.
I have installed the package as explained inside the docs, and it works like a charm on iOS.

Though, on Android it doesn't. So I'm wondering, does this package work properly with Expo ? Or is it only for apps that are made with RN-CLI ?

N.B: I'm using openInbox() function, without any parameters.

Thank you for your help,
Mika

**Comment by tschoffelen** [comment]
Unfortunately, it does not, since this package needs some native code on Android to provide its functionality. I can't see a way at the moment to implement that using Expo.
