### ISSUE TITLE
TypeScript support for iOS expanded functionality

### ISSUE THREAD

**Issue by ObidosDev** [tschoffelen/react-native-email-link#56]
I have discovered that iOS has a little bit more functionality than described in doc. So it should be developed stub for android and normal d.ts done too

**Comment by tschoffelen** [comment]
Hi, good point. I think some recent additions might not have been reflected in the d.ts yet. Any chance you could do a PR?

**Comment by tschoffelen** [comment]
The `index.d.ts` currently actually reflects the functionality pretty well. The only inconsistency is that the `cc` and `bcc` fields are currently not available on Android, but that should change soon.

Closing this one for now, but do feel free to open a PR if you still think the `index.d.ts` file needs a bit more work. Thanks!
