### ISSUE TITLE
Not open mail App in Android 

### ISSUE THREAD

**Issue by yogendragirase55** [tschoffelen/react-native-email-link#57]
I am using this code: 
`openInbox({
	message: 'Whatcha wanna do?',
	cancelLabel: 'Go back!'
})`
getting possiable anhandled promise rejection (id:5)

**Comment by tschoffelen** [comment]
If this is still a problem, let's chat in #59

**Comment by tiger01815** [comment]
![image](https://github.com/user-attachments/assets/627af3bf-9ade-4791-a065-f3629bdcb087)
I was going to open the email inbox in react native using react-native-email-link.
But the app can't launch the email app and there are no anything warning or error.
What should I do to resolve this?
