### ISSUE TITLE
openInbox not working on Android

### ISSUE THREAD

**Issue by awkpagong** [tschoffelen/react-native-email-link#59]
When calling `openInbox()` on Android I'm getting the following error: `TypeError: null is not an object (evaluating '_reactNative.NativeModules.Email.open')`.  I am guessing there is something wrong with the auto-linking but I do not have enough expertise to troubleshoot the problem.  I am on react-native version 62.2.  Any help would be greatly appreciated!

<img width="501" alt="Screenshot 2020-04-13 17 28 55" src="https://user-images.githubusercontent.com/33337326/79164189-88bb9e00-7dae-11ea-961c-b3c374bb26d7.png">

**Comment by tschoffelen** [comment]
Did you rebuild the app and clean any caches after installing the library?

**Comment by awkpagong** [comment]
@tschoffelen I tried doing `watchman watch-del-all && rm -f yarn.lock && rm -rf node_modules && yarn && yarn start --reset-cache`. Is there something else I should try? Note: I am using an ejected expo app.

**Comment by tschoffelen** [comment]
That's all fine for the javascript side, but did you also rebuild the native part of the app (e.g. using `react-native run-android`)?

**Comment by awkpagong** [comment]
> That's all fine for the javascript side, but did you also rebuild the native part of the app (e.g. using `react-native run-android`)?

@tschoffelen yes I also did `npx react-native run-android` but the error is still occurring. Any idea what else might be causing the issue?

**Comment by joaosousafranco** [comment]
Ive just tested this in android and it works after rebuilding the native app, i believe this can be closed.

**Comment by tschoffelen** [comment]
I think so too, thanks @joaosousafranco! :)
