### ISSUE TITLE
Html not working

### ISSUE THREAD

**Issue by acollazomayer** [tschoffelen/react-native-email-link#60]
I am passing html on the body of my email and is not being recongnized. Any idea why this might be happening?

**Comment by kenkotch** [comment]
html seems to be working everywhere except gmail and outlook. Any idea why?

**Comment by tschoffelen** [comment]
It looks like neither of those clients support that at the moment unfortunately:

* [Outlook](https://stackoverflow.com/questions/59257114/how-to-configure-html-body-for-ms-outlook-compose-body-parameter-for-outlook-f) - seems to have worked at some point, then it didn't, then it did again, and now it looks like it doesn't work anymore.
* [Gmail](https://stackoverflow.com/questions/45000702/having-an-html-body-when-using-the-gmail-url-scheme-in-swift-3) - only resource I could find online asking the same question, has stayed unanswered, and I can't find any official documentation from Google about the URL scheme.

**Comment by kenkotch** [comment]
thank you for the fast reply @tschoffelen 
too bad there is no workaround...yet

**Comment by tschoffelen** [comment]
Yep... Seems like something that you'd expect to be supported by everyone...

Since it's not a limitation of this library, but rather of the email clients themselves, is it okay if I close this issue for now?
