### ISSUE TITLE
[Android] body argument in openComposer() can't handle text after question marks

### ISSUE THREAD

**Issue by mvanroon** [tschoffelen/react-native-email-link#62]
@gekitz recently implemented Android support for this library (thanks!) 

however when I use his/her fork (https://github.com/muratakkas/react-native-email-link/tree/fix/newtask_crash) and compose an email which contains a URL with query parameters, all the text after the question marks is removed:

![IMG_3484](https://user-images.githubusercontent.com/1309448/79869804-3dbf0d80-83e2-11ea-8a49-cb19bec5bcec.png)

while it does work on iOS:

![IMG_3485](https://user-images.githubusercontent.com/1309448/79869849-529ba100-83e2-11ea-8fee-68b08e8afe99.PNG)

I believe this has to do with the following line:

https://github.com/tschoffelen/react-native-email-link/blob/db1ef97b15578e3a5ba09d1b35d4421db96280e9/android/src/main/java/com/facebook/react/modules/email/EmailModule.java#L71

I now use https://github.com/lucasferreira/react-native-send-intent on android devices to send emails which works great. Perhaps their source code can be of any help. Sorry I can't be of more help. I am not much of a java programmer :-)

**Comment by gekitz** [comment]
just a hunch, but I guess we’ll have to url-encode this and it will work. I’ll have to try it.

**Comment by mvanroon** [comment]
I've tried this before by putting a mailto: link in Linking.openUrl() and encoding the parameters, but I didn't work
