### ISSUE TITLE
Can't catch error if no Email client

### ISSUE THREAD

**Issue by dbilgin** [tschoffelen/react-native-email-link#69]
Hi there, I can't seem to catch any errors when there was no email client on my iOS simulator.

```
  async openEmail() {
    try {
      await openInbox({
        message: 'select',
        cancelLabel: 'cancel',
      });
    } catch (error) {
      alert();
    }
  }
```

It doesn't get to the catch statement at all, but I do get a warning on the simulator as below:

<img width="401" alt="Screenshot 2020-05-11 at 12 18 37" src="https://user-images.githubusercontent.com/15243788/81551097-8d5d7d00-9381-11ea-9f9d-26cb16718a67.png">

Am I doing something wrong or is there a problem here?

**Comment by tschoffelen** [comment]
Good catch! (sorry, I couldn't resist 😄)

I think I found the problem, and just released `react-native-email-link@1.8.2` that hopefully fixes it. Would you mind giving it a try? Don't have a dev environment set up to test it myself at the moment.

**Comment by dbilgin** [comment]
😄 my pleasure! @tschoffelen 
And I just tried it and it seems it's fixed, thanks a lot for the fast response!

**Comment by tschoffelen** [comment]
Happy to hear!
