### ISSUE TITLE
openInbox does not show an action sheet but directly opens the mail

### ISSUE THREAD

**Issue by kidroca** [tschoffelen/react-native-email-link#72]
Reading the possible options I would expect that providing options would trigger a prompt with the configured items:

```js
openInbox({
  title: 'Please verify your email so you can recover your account',
  message: `A verification email was sent to ${ email }`,
  cancelLabel: 'Close',
});
```

Instead the mail app is directly opened

An Action Sheet appears only when there are more than one mailing apps - maybe that behavior should be documented

**Comment by tschoffelen** [comment]
Hi! Good point that we don't explicitly note that in the README at the moment.

 Most of the uses of this library entail a screen with a button labeled something like 'Open inbox', in which case it makes sense that it only shows an ActionSheet with multiple options if there is more than a single option.
