### ISSUE TITLE
Add error when no mail apps are available on iOS

### ISSUE THREAD

**Issue by tschoffelen** [tschoffelen/react-native-email-link#8]
When no email apps are available to open at all, the library should show an error. 

Currently the lack of this causes it to look like it isn't working at all on the iOS Simulator (#3), since Mail.app is not installed on there by default.

**Comment by tschoffelen** [comment]
Thanks to the changes by @cesar3030 an `EmailException` is now thrown, which is sufficient to mark this as fixed! 🎉

**Comment by berkaey** [comment]
@tschoffelen 

trying to catch that like below, but it won't, is there any specific use case?

```
try {
  openInbox();
} catch (e) {
  console.log(e);
}```

**Comment by berkaey** [comment]
🤦‍♂️ for anybody else...

```
openInbox().catch(e =>
 console.log(e)
});
```

**Comment by tschoffelen** [comment]
Hi @berkaey, the reason that your first code snippet didn't work is that `openInbox()` is async, so you'd need an `await` in there:

```
try {
  await openInbox();
} catch (e) {
  console.log(e);
}
```
